export const FETCH_ALL_MENTOR_DATA="FETCH_MENTOR_DATA";
export const FETCH_ALL_MENTOR_DATA_START="FETCH_MENTOR_DATA_START"
export const FETCH_ALL_MENTOR_DATA_SUCCESS=" FETCH_ALL_MENTOR_DATA_SUCCESS"
export const FETCH_ALL_MENTOR_DATA_FAIL="FETCH_ALL_MENTOR_DATA_FAIL"


export const TAKE_A_MENTOR="TAKE_A_MENTOR";


export const UPDATE_A_MENTOR_DATA="UPDATE_A_MENTOR_DATA";
export const UPDATE_A_MENTOR_DATA_START="UPDATE_A_MENTOR_DATA_START";
export const UPDATE_A_MENTOR_DATA_SUCCESS="UPDATE_A_MENTOR_DATA_SUCCESS";
export const UPDATE_A_MENTOR_DATA_FAIL="UPDATE_A_MENTOR_DATA_FAIL";

export const DELETE_A_MENTOR="DELETE_A_MENTOR";
export const DELETE_A_MENTOR_START="DELETE_A_MENTOR_START";
export const DELETE_A_MENTOR_SUCCESS="DELETE_A_MENTOR_SUCCESS";
export const DELETE_A_MENTOR_FAIL="DELETE_A_MENTOR_FAIL";


export const AUTH_SIGNUP="AUTH_SIGNUP";
export const AUTH_START="AUTH_START";
export const AUTH_SUCCESSS="AUTH_SUCCESSS";
export const AUTH_FAIL="AUTH_FAIL";

export const AUTH_INITIATE_LOGOUT="AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT="AUTH_LOGOUT";

